main: net.lazlecraft.hubkick.HubKick
author: LaxWasHere
version: ${project.version}
name: HubKick
commands:
    hub:
        description: Sends you to the hub server!
        aliases: lobby
        permission: hubkick.command
        permission-message: You shall not pass!
    alltolobby:
        description: Sends everyone to the hub server!
        aliases: [lobbyall, allto]
        permission: hubkick.kickall
        permission-message: You may not!
    shutdown:
        description: Sends everyone to the hub server and shutdown the server.
        aliases: stop
        permission: hubkick.shutdown
        permission-message: You shall not pass!
    forcekick:
        description: Crashes the players client
        aliases: fkick
        permission: hubkick.forcekick
        permission-message: You may not kick!
    sendplayer:
        description: Send the player to another server.
        aliases: sendp
        permission: hubkick.send
        permission-message: You may not send!
